---
name: 'ZPL Preview Release'
on:
  push:
  # release:
  #   types:
  #     - 'published'
jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install vsce
        run: npm install -g vsce
      - name: Publish
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
